### ISSUE TITLE
What is hubURI and port

### ISSUE THREAD

**Issue by Hjgaming** [FC5570/Discord-Youtube-Notifier-Bot-V2#1]
What is hubURI and port i send request on discord my name is hj gaming pls reply

**Comment by FC5570** [comment]
`port` is the port your express server will run on.
`hubURI` is the your ip and port in a url format, like `http://ip:port` the port here would be there port your express server is running on. 

Please read the readme once again, or look at this [package](https://www.npmjs.com/package/youtube-notification) for more info.
